version: '3'
volumes:
  database-volume:
  logs:
services:

  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    volumes:
      - database-volume:/var/lib/mysql
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: 'spe/goalbook'
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/demo?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    volumes:
      - logs:/logs
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
  frontend:
    image: 'adwait2210/goalbookfe'
    ports:
      - "3000:3000"
    depends_on:
      - springboot-docker-container
